name: ci

on:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: 
          - x86_64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
        crate:
          - starship
          - sccache
          - cargo-bloat
          - cargo-edit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Rust toolchain
        uses: action-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: ${{ matrix.target }}
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        env:
          CC: clang
          RUSTFLAGS: "-C linker=rust-lld -C linker-flavor=ld.lld"
          CARGO_INSTALL_ROOT: /tmp/${{ matrix.target }}
        with:
          use-cross: true
          command: install
          args: --target ${{ matrix.target }} ${{ matrix.crate }}

