name: ci

on:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: 
          - x86_64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
        crate:
          - "sccache --no-default-features"
    steps:
      - name: install musl
        run: sudo apt-get install -y musl-dev libssl-dev g++-multilib clang

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: ${{ matrix.target }}
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        env:
          CC: clang
          RUSTFLAGS: "-C linker=rust-lld -C linker-flavor=ld.lld"
          CARGO_INSTALL_ROOT: /tmp/dist/${{ matrix.target }}
        with:
          command: install
          args: --target ${{ matrix.target }} ${{ matrix.crate }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: /tmp/dist

